spring.application.name=Enterprise_Application
spring.datasource.url=JOUW_DB_URL_DB_POORT_DB_NAAM
spring.datasource.username=JOUW_GEBRUIKERSNAAM
spring.datasource.password=JOUW_WACHTWOORD

# SMTP configuratie
spring.mail.host=JOUW_MAILSERVER
spring.mail.port=0
spring.mail.username=JOUW_EMAILADRES
spring.mail.password=JOUW_EMAILWACHTWOORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
